using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HeroController : MonoBehaviour
{
    public float speed = 3.0f;    //ï¿½Ú“ï¿½ï¿½Xï¿½sï¿½[ï¿½h
    int direction = 0;            //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½
    float axisH;                  //ï¿½ï¿½ï¿½ï¿½
    float axisV;                  //ï¿½cï¿½ï¿½
    public float angleZ = -90.0f; //ï¿½ï¿½]ï¿½pï¿½x
    Rigidbody2D rbody;            //Rigidbody2D
    Animator animator;            //Animator
    bool isMoving = false;        //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O

    //p1ï¿½ï¿½ï¿½ï¿½p2ï¿½ÌŠpï¿½xï¿½ï¿½Ô‚ï¿½
    float GetAngle(Vector2 p1, Vector2 p2)
    {
        float angle;
        if (axisH != 0 || axisV != 0)
        {
            //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½ÎŠpï¿½xï¿½ï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½
            //p1ï¿½ï¿½ï¿½ï¿½p2ï¿½Ö‚Ìï¿½ï¿½ï¿½ï¿½iï¿½ï¿½ï¿½_ï¿½ï¿½0ï¿½É‚ï¿½ï¿½é‚½ï¿½ßj
            float dx = p2.x - p1.x;
            float dy = p2.y - p1.y;
            //ï¿½Aï¿½[ï¿½Nï¿½^ï¿½ï¿½ï¿½Wï¿½Fï¿½ï¿½ï¿½gï¿½Qï¿½Öï¿½ï¿½ÅŠpï¿½xï¿½iï¿½ï¿½ï¿½Wï¿½Aï¿½ï¿½ï¿½jï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
            float rad = Mathf.Atan2(dy, dx);
            //ï¿½ï¿½ï¿½Wï¿½Aï¿½ï¿½ï¿½ï¿½xï¿½É•ÏŠï¿½ï¿½ï¿½ï¿½Ä•Ô‚ï¿½
            angle = rad * Mathf.Rad2Deg;
        }
        else
        {
            //ï¿½ï¿½~ï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½ÎˆÈ‘Oï¿½ÌŠpï¿½xï¿½ï¿½ï¿½Ûï¿½
            angle = angleZ;
        }
        return angle;
    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        rbody = GetComponent<Rigidbody2D>();    //Rigidbody2Dï¿½ğ“¾‚ï¿½
        animator = GetComponent<Animator>();    //Animatorï¿½ğ“¾‚ï¿½
    }

    // Update is called once per frame
    void Update()
    {
        if (isMoving == false)
        {
            axisH = Input.GetAxisRaw("Horizontal");   //ï¿½ï¿½ï¿½Eï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½
            axisV = Input.GetAxisRaw("Vertical");     //ï¿½ã‰ºï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½
        }
        //ï¿½Lï¿½[ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½Ú“ï¿½ï¿½pï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
        Vector2 fromPt = transform.position;
        Vector2 toPt = new Vector2(fromPt.x + axisH, fromPt.y + axisV);
        angleZ = GetAngle(fromPt, toPt);
        //ï¿½Ú“ï¿½ï¿½pï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÆƒAï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½V
        int dir;
        if (angleZ >= -45 && angleZ < 45)
        {
            //ï¿½Eï¿½ï¿½ï¿½ï¿½
            dir = 3;
        }
        else if (angleZ >= 45 && angleZ <= 135)
        {
            //ï¿½ï¿½ï¿½ï¿½ï¿½
            dir = 2;
        }
        else if (angleZ >= -135 && angleZ <= -45)
        {
            //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            dir = 0;
        }
        else
        {
            //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            dir = 1;
        }
        if (dir != direction)
        {
            direction = dir;
            animator.SetInteger("Direction", direction);
        }
    }

    private void FixedUpdate()
    {
        //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½
        rbody.linearVelocity = new Vector2(axisH, axisV). normalized* speed;
    }

    public void SetAxis(float h, float v)
    {
        axisH = h;
        axisV = v;
        if (axisH == 0 && axisV == 0)
        {
            isMoving = false;
        }
        else
        {
            isMoving = true;
        }
    }
}
